app = "tabungan-pontra"
primary_region = "sin"
[build]
[env]
  PORT = "3000"
  DATA_DIR = "/data"
[[mounts]]
  source = "tabungan_data"
  destination = "/data"
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    path = "/"
    timeout = "2s"
